mysite/blog/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostsFeed


app_name = 'blog'
urlpatterns = [
    # Widoki posta
    path('', views.post_list, name='post_list'),
    # path('', views.PostListView.as_view(), name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_details, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('search/', views.post_search, name='post_search'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap


sitemaps = {
    'post': PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path(
        'sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'
    ),
]

mysite/blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(
        max_length=250,
        unique_for_date='publish',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='blog_posts',
    )
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(
        max_length=10,
        choices=STATUS_CHOICES,
        default='draft',
    )

    objects = models.Manager()   # domyslny manager
    published = PublishedManager()   # niestandardowy manager

    tags = TaggableManager()   # manager umożliwia dodawanie, pobieranie usuwanie tagóœ z obiektu Post

    class Meta:
        ordering = ('-publish',)
        db_table = 'music_posts_blog'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse(
            'blog:post_detail',  # z urls przetrzeń nazwy + nazwa urla
            args=[self.publish.year, self.publish.month, self.publish.day, self.slug]
        )


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
    )
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return 'Komentazr dodany prze {} dla posta {}'.format(self.name, self.post)

mysite/blog/forms.py
from django import forms
from .models import Comment


#  dwie klasy bazowe do tworzenia formlarzy: Form i ModelForm

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(
        required=False,
        widget=forms.Textarea,
    )


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')


class SearchForm(forms.Form):
    query = forms.CharField()

mysite/blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Comment
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from .forms import EmailPostForm, CommentForm, SearchForm
from django.core.mail import send_mail
from taggit.models import Tag
from django.db.models import Count
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank, TrigramSimilarity


# def post_list(request):
#     posts = Post.published.all()
#     return render(
#         request,
#         'blog/post/list.html',
#         {
#             'posts': posts,
#         }
#     )


def post_list(request, tag_slug=None):
    object_list = Post.published.all()
    tag = None

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])  # tags__in - bo manager się nazywa tags

    paginator = Paginator(object_list, 3)   # liczba postów na str
    page = request.GET.get('page')          # nr bieżącej str

    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # jeśli page nie jest integerem, pobież 1 str
        posts = paginator.page(1)
    except EmptyPage:
        # jesli page > od ost str, wyświetl ost str
        # ost str (paginator.num_pages)
        posts = paginator.page(paginator.num_pages)
    return render(
        request,
        'blog/post/list.html',
        {
            'page': page,
            'tag': tag,
            'posts': posts,     # jeśli widok oparty na def, w paginacji
                               # {% include "pagination.html" with page=posts %}
        }
    )


# class PostListView(ListView):
#     # queryset = Post.published.all()   # możemy zostać przy model = Post a Django za nas przygotuje kolecję
#                                         # QuerySet Post.published.all()
#     model = Post
#     context_object_name = 'posts'
#     paginate_by = 3
#     template_name = 'blog/post/list.html'


def post_details(request, year, month, day, post):
    post = get_object_or_404(
        Post,
        slug=post,
        status='published',
        publish__year=year,
        publish__month=month,
        publish__day=day,
    )
    # lista aktywnych komentarzy dla posta wyciągniętego wyżej
    comments = post.comments.filter(active=True)
    new_comment_add = False

    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            #  tworzymy nowy komentarz na podstawie wysłanych danych
            #  ale jeszcze go nie zapisujemy do bazy
            new_comment = comment_form.save(commit=False)
            #  przypisujemy go do posta
            new_comment.post = post
            #  zapisuejmy w bazie
            new_comment.save()
            new_comment_add = True
    else:
    # if request.method == 'GET':
        comment_form = CommentForm()

    # Lista podobnych postów
    post_tags_ids = post.tags.values_list('id', flat=True)
        #  pobieramy listę idików tagów, które są też chakterystyczne dla bieżącego posta
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
        #  pobieramy wyżej wszystkie posty zawierające dowolny z otrzymanych wczeniej tag, poza bieżącym
    similar_posts = similar_posts.annotate(same_tags=Count('tags')) \
                        .order_by('-same_tags', '-publish')[:4]

    if len(comments) == 1:
        comments_pl_ending = ''
    elif len(comments) in (2, 3, 4):
        comments_pl_ending = 'e'
    else:
        comments_pl_ending = 'y'

    return render(
        request,
        'blog/post/detail.html',
        {
            'post': post,
            'comments': comments,
            'comment_form': comment_form,
            'new_comment_add': new_comment_add,
            'similar_posts': similar_posts,
            'comments_pl_ending': comments_pl_ending,
        }
    )


def post_share(request, post_id):
    #  pobieranie posta na podst. jego identyfikatora
    post = get_object_or_404(
        Post,
        id=post_id,
        status='published',
    )
    sent = False

    if request.method == 'POST':
        form = EmailPostForm(request.POST)  # tworzymy formularz na podst. wysłanych danych z request.POST
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(
                post.get_absolute_url()
            )
            subject = 'według {0} (a to ichni mail{1}) mówi, że "{2}" jest ok'.format(
                cd['name'], cd['email'], post.title
            )
            message = 'Jak coś "{0}" jest tu {1}\n\n{2}\ skomentował tak: {3}'.format(
                post.title, post_url, cd['name'], cd['comments']
            )
            send_mail(subject, message, 'od kogo', [cd['to']])
            sent = True
    else:
        form = EmailPostForm()
    return render(
        request,
        'blog/post/share.html',
        {
            'post': post,
            'form': form,
            'sent': sent,
        }
    )


def post_search(request):
    form = SearchForm()
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            # search_vector = SearchVector('title', 'body')
            # search_query = SearchQuery(query)
            # results =Post.objects.annotate(
            #     search=search_vector,
            #     rank=SearchRank(search_vector, search_query)
            # ).filter(search=search_query).order_by('-rank')

            results = Post.objects.annotate(
                similarity=TrigramSimilarity('title', query),
            ).filter(similarity__gt=0.3).order_by('-similarity')
    return render(
        request,
        'blog/post/search.html',
        {
            'form': form,
            'query': query,
            'results': results
        }
    )

mysite/blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
  <h1>{{ post.title }}</h1>
  <p class="date">
    wypracowany w pocie czoła {{ post.publish }} ręcami {{ post.author }}
  </p>
  {{ post.body|markdown_filtr}}
  <p>
    <a href="{% url "blog:post_share" post.id %}">
      Udostepnij
    </a>
  </p>

  <h2>całkiem podobne posty, czeknij:</h2>
  {% for post in similar_posts %}
    <p>
      <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </p>
  {% empty %}
    Nikt nie napisał jeszcze czegoś podobnego
  {% endfor %}

  {% with comments.count as total_comments %}
    <h2>
      {{ total_comments }} komenatrz{{ comments_pl_ending }}
    </h2>
  {% endwith %}
  {% for comment in comments %}
    <div class="comment">
      <p class="info">
        Komentarz {{ forloop.counter }} dodany przez {{ comment.name }}
        {{ comment.created }}
      </p>
      {{ comment.body|linebreaks }}
    </div>
  {% empty %}
    <p>no nie ma jeszcze żadnych komentów</p>
  {% endfor %}

  {% if new_comment_add %}
    <h2>dodałeś komemntarz, grasty</h2>
  {% else %}
    <h2>jakiś komentarzyk</h2>
    <form action="." method="post">
      {{ comment_form.as_p }}
      {% csrf_token %}
      <p><input type="submit" value="skomentowane"></p>
    </form>
  {% endif %}
{% endblock %}

mysite/blog/templates/blog/post/latest_post.html
<ul>
{% for post in latest_posts %}
  <li>
    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
  </li>
{% endfor %}
</ul>

mysite/blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title %}main blog{% endblock %}

{% block content %}
  <h1>to jest moj i tylko mój blog</h1>
  {% if tag %}
    <h2>posty oznaczone tagiem "{{ tag.name }}"</h2>
  {% endif %}
  {% for post in posts %}
    <h2>
      <a href="{{ post.get_absolute_url }}">
        {{ post.title }}
      </a>
    </h2>
    <p class="tags">
      Tagi:
      {% for tag in post.tags.all %}
        <a href="{% url "blog:post_list_by_tag" tag.slug %}">
          {{ tag.name }}
        </a>
        {% if not forloop.last %}, {% endif %}
      {% endfor %}
    </p>
    <p class="date">
      opublikowany {{ post.publish }} przez {{ post.author }}
    </p>
    {{ post.body|markdown_filtr|truncatewords_html:30 }}
  {% endfor %}
  {% include "pagination.html" with page=posts %}
{% endblock %}

mysite/blog/templates/blog/post/search.html
{% extends "blog/base.html" %}

{% block title %}Wyszukaj{% endblock %}

{% block content %}
  {% if query %}
    <h1>Posty zawierające: "{{ query }}"</h1>
    <h3>
      {% with results.count as total_results %}
          Znalezione {{ total_results }} takie coś
      {% endwith %}
    </h3>
    {% for post in results %}
        <h4><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h4>
        {{ post.body|truncatewords:5 }}
    {% empty %}
      <p>No nie ma, mów co chcesz ale nie ma</p>
    {% endfor %}
    <p><a href="{% url "blog:post_search" %}">jeszcze raz </a></p>
  {% else %}
    <h1>szukaj postów, gdzie muszą być</h1>
    <form action="." method="get">
      {{ form.as_p }}
      <input type="submit" value="Szukajcie z znajdziecie">
    </form>
  {% endif %}
{% endblock %}

mysite/blog/templates/blog/post/share.html
{% extends "blog/base.html" %}

{% block title %}Udostępnij post{% endblock %}

{% block content %}
  {% if sent %}
    <h1>E-mail wysłany, well done</h1>
    <p>
      wysłanie info o tym fantastycznym "{{ post.title }}" na email {{ form.cleaned_data.to }} się udało się.
    </p>
  {% else %}
    <h1>Udostępnij "{{ post.title }}" komuś majlem </h1>
    <form action="." method="post">
      {{ form.as_p }}
      {% csrf_token %}
      <input type="submit" value="wyślij tegoż maila">
    </form>
  {% endif %}
{% endblock %}